// Copyright (c) Meta Platforms, Inc. and affiliates.

#include "OculusXRColocationEventDelegates.h"

FOculusXRColocationEventDelegates::FStartColocationAdvertisementComplete FOculusXRColocationEventDelegates::StartColocationAdvertisementComplete;
FOculusXRColocationEventDelegates::FStopColocationAdvertisementComplete FOculusXRColocationEventDelegates::StopColocationAdvertisementComplete;
FOculusXRColocationEventDelegates::FColocationAdvertisementComplete FOculusXRColocationEventDelegates::ColocationAdvertisementComplete;

FOculusXRColocationEventDelegates::FStartColocationDiscoveryComplete FOculusXRColocationEventDelegates::StartColocationDiscoveryComplete;
FOculusXRColocationEventDelegates::FStopColocationDiscoveryComplete FOculusXRColocationEventDelegates::StopColocationDiscoveryComplete;
FOculusXRColocationEventDelegates::FColocationDiscoveryComplete FOculusXRColocationEventDelegates::ColocationDiscoveryComplete;
FOculusXRColocationEventDelegates::FColocationDiscoveryResultAvailable FOculusXRColocationEventDelegates::ColocationDiscoveryResultAvailable;
